### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [Chan4077/StudyBuddy#7]
![sb-logo](https://user-images.githubusercontent.com/36993664/39194814-29d862e6-47e7-11e8-8cbc-2655c3397ea8.jpg)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

**Comment by Yasujizr** [comment]
If you like it, I send PR? Or you want any change on logo?

**Comment by Chan4077** [comment]
@Yasujizr How about a different colour? Maybe the app's primary colour?

Otherwise, it's good to go! :+1:

**Comment by Chan4077** [comment]
@Yasujizr Any updates?

**Comment by Yasujizr** [comment]
![sb-logo](https://user-images.githubusercontent.com/36993664/39377546-31a006f4-4a5e-11e8-86e2-41032f3732c7.jpg)

Hi,

I updatae on Logo Color, Logotype and Notification Icon.

**Comment by Yasujizr** [comment]
Hi, 

Do you like it? If you approve, what sizes I send u?

**Comment by Chan4077** [comment]
@Yasujizr Ideally, it should be an adaptive icon to support for those who are running Android Oreo.

There should also be an additional icon for those running Android Nougat and older

**Comment by Yasujizr** [comment]
512px to 48px and svg. png. eps. pdf file. Is it appropriate for you?

**Comment by Chan4077** [comment]
@Yasujizr It's appropriate

**Comment by Yasujizr** [comment]
All File in this Drive Link; https://drive.google.com/open?id=1Hr3cxvVmhR69chMKxPmwMqUkfHrA666d

**Comment by Yasujizr** [comment]
Hi,

I send PR, but I don't know write code, therefore I can't add notification icons. But I update Drive, add notification icons svg.

**Comment by Yasujizr** [comment]
@Chan4077  Thank you for your liking. I updated PR, I hope, I have done in this time. 👍

**Comment by Chan4077** [comment]
I've merged your PR. Thanks!

**Comment by Chan4077** [comment]
Sorry to bother you, but could I have the color/colour palette modified to match the new colours?

Thanks for your icon design!
